-- Supabase PostgreSQL tables

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    level INTEGER DEFAULT 0,
    is_banned BOOLEAN DEFAULT FALSE,
    ban_until TIMESTAMPTZ NULL,
    temp_email TEXT NULL,
    temp_password TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    order_number TEXT NOT NULL,
    platform TEXT NOT NULL,
    email TEXT NOT NULL,
    platform_password TEXT NOT NULL,
    level INTEGER NOT NULL,
    charged_before TEXT NOT NULL,
    diamonds INTEGER NOT NULL,
    delivery_time TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    rejection_reason TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    message_id TEXT NOT NULL,
    from_address TEXT NOT NULL,
    from_name TEXT,
    subject TEXT,
    intro TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, message_id)
);
