-- Supabase PostgreSQL tables

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    level INTEGER DEFAULT 0,
    is_banned BOOLEAN DEFAULT FALSE,
    ban_until TIMESTAMPTZ NULL,
    temp_email TEXT NULL,
    temp_password TEXT NULL,
    original_email TEXT NULL,
    id_account TEXT NULL,
    verification_status TEXT DEFAULT 'Pending',
    level_status TEXT DEFAULT 'Pending',
    linking_status TEXT DEFAULT 'Pending',
    account_name TEXT NULL,
    ban_cause TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    order_number TEXT NOT NULL,
    platform TEXT NOT NULL,
    email TEXT NOT NULL,
    original_email TEXT NULL,
    platform_password TEXT NOT NULL,
    level INTEGER NOT NULL,
    charged_before TEXT NOT NULL,
    diamonds INTEGER NOT NULL,
    delivery_time TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    rejection_reason TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    message_id TEXT NOT NULL,
    from_address TEXT NOT NULL,
    from_name TEXT,
    subject TEXT,
    intro TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, message_id)
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migration Scripts (Run these to update existing tables without losing data)
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS original_email TEXT NULL;
-- ALTER TABLE orders ADD COLUMN IF NOT EXISTS original_email TEXT NULL;
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS id_account TEXT NULL;
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS verification_status TEXT DEFAULT 'Pending';
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS level_status TEXT DEFAULT 'Pending';
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS linking_status TEXT DEFAULT 'Pending';
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS account_name TEXT NULL;
-- ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_cause TEXT NULL;

